/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF('/Enemy9.gltf');
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions.Sphere1Action.play();
		actions.Sphere2Action.play();
		actions.Sphere3Action.play();
		actions.Sphere4Action.play();
		actions.TorusAction.play();
		actions.Torus1Action.play();
		actions.Torus2Action.play();
	});

	return (
		<group ref={group} {...props} dispose={null}>
			<mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.Ship1FaceMaterial} scale={0.3} />
			<mesh
				name="Torus"
				geometry={nodes.Torus.geometry}
				material={nodes.Torus.material}
				position={[-0.04, 0.08, -0.04]}
				scale={[1.28, -0.12, 1.23]}
			/>
			<mesh
				name="Torus1"
				geometry={nodes.Torus1.geometry}
				material={nodes.Torus1.material}
				position={[0.01, 0.02, -0.01]}
				rotation={[-0.58, -0.05, 0.01]}
				scale={[0.44, -0.04, 0.42]}
			/>
			<mesh
				name="Torus2"
				geometry={nodes.Torus2.geometry}
				material={nodes.Torus2.material}
				position={[0, 0.03, -0.02]}
				rotation={[-2.06, -0.26, 0.65]}
				scale={[0.72, -0.07, 0.69]}
			/>
			<mesh
				name="Sphere1"
				geometry={nodes.Sphere1.geometry}
				material={nodes.Sphere1.material}
				position={[1.16, 0.76, -0.21]}
				scale={0.11}
			/>
			<mesh
				name="Sphere2"
				geometry={nodes.Sphere2.geometry}
				material={nodes.Sphere2.material}
				position={[-0.16, 0.14, -0.74]}
				scale={0.11}
			/>
			<mesh
				name="Sphere3"
				geometry={nodes.Sphere3.geometry}
				material={nodes.Sphere3.material}
				position={[0.96, -0.53, 0.24]}
				scale={0.11}
			/>
			<mesh
				name="Sphere4"
				geometry={nodes.Sphere4.geometry}
				material={nodes.Sphere4.material}
				position={[-0.65, -0.32, -0.41]}
				scale={0.11}
			/>
		</group>
	);
}

useGLTF.preload('/Enemy9.gltf');
