/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Enemy1({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Enemy1.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Cube003"
        geometry={nodes.Cube003.geometry}
        material={materials.walkingcubefeet}
        position={[0.01, 0.61, 0.02]}
        scale={0.36}
      />
      <mesh
        name="Cube"
        geometry={nodes.Cube.geometry}
        material={materials['Material.004']}
        position={[0.11, 2.08, 0]}
        scale={0.36}
      />
      <mesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={materials['Material.005']}
        position={[0, 2.09, 0.01]}
        scale={0.36}
      />
    </group>
  )
}

useGLTF.preload('../../Enemy1.glb')
