/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Enemy10.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.CubeAction.play();
    actions.SphereAction.play();
    actions.SphereAction2.play();
    actions.TorusAction1.play();
    actions.TorusAction2.play();
    actions.TorusAction3.play();
    actions.TorusAction4.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Sphere001"
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[0.03, 0.03, 0.03]}
        scale={1.01}
      />
      <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[0.03, 0.03, 0.03]}
        scale={1.01}
      />
      <mesh
        name="Cube"
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[0.05, -0.5, -0.06]}
        scale={0.23}
      />
      <mesh
        name="Torus"
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[0.06, -1.18, -0.01]}
        scale={0.85}
      />
      <mesh
        name="Torus001"
        geometry={nodes.Torus001.geometry}
        material={materials.Material2}
        position={[0.01, 0.09, 1.16]}
        rotation={[1.51, 0.19, 0.08]}
        scale={[0.56, 0.56, 0.56]}
      />
      <mesh
        name="Torus002"
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[0, 0.11, 1.26]}
        rotation={[1.51, 0.19, 0.08]}
        scale={[0.18, 0.18, 0.18]}
      />
      <mesh
        name="Torus003"
        geometry={nodes.Torus003.geometry}
        material={nodes.Torus003.material}
        position={[0.01, 0.09, 1.16]}
        rotation={[1.51, 0.19, 0.08]}
        scale={[0.23, 0.23, 0.23]}
      />
    </group>
  )
}

useGLTF.preload('/Enemy10.gltf')
